sudo: false
language: rust
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev
    - cmake
    sources:
    - kalakris-cmake

rust:
- stable 
- beta
- nightly
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATHi &&
  cargo install cargo-travis &&
  export PATH=$HOME/.cargo/bin:$PATH

script:
- |
  cargo build &&
  cargo test &&
  cargo bench &&
  cargo --only stable doc
after_success:
- travis-cargo --only stable doc-upload
- cargo coveralls
env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=""
  - secure: hM5NWf4BtwfNZAPossbvQxYJ7WeJLeRymVT473O1wHrz6xisWqagV0f2fR2Jcr5fGInufDlIkdqiDvxWC++qaCkMhGf6QQKxvqCRUc+CZAqQ0AsAxYENwy2VQduj1IfGc+Xdl4F4vaMFpEiJ2gvl8tDfc+ZIubfdBrVTMBmMy/HWK4Wi/XMeIXrPBLke5Hxrqf3zftvmwgSLhZNQzdXbSdRyo1KRx0lcRIlCQ/XF/zKIifG30MyAg3iZTeH7OaDgAXBsM5o4kTkVJhMxRV1Qa0XdzTsExAUsuPUnHjIu3EYxDP11PTbWCdkT/aS9qr+z/4a5HQP5NBDJapdYOPCfYS5xREt0e5FD0iVg/DeKEEfvhmwTf8czMspUdFILUYorU0TKGUygDK7UUl79cmFNq4zQ9BeQ53dZ5JnQT5fd7QIq9p7O2c0vLcexkA0YewktaR2kkLljfqNBFncW5NSlINAM7apPkIcq5Wm768xDn3ZTd9n+gHl69s/zLrCN42dj4RMH2MJBn9m9K+cbzxtRdhgw1JGVdjNMu7pW32pZtH6WUCpSJCmr/NJwIVGLZRnaMnjAwVUP+bzRRGmzEXx5C2KAH2Tctu80hVzXSCAIVlEqPYAXaGPrNfNv5mL46w4/C7PossUFRbvwaqvyPHAMYDSfnoX2YTBsH1eqvNX64X4=
